# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'guid.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(796, 650)
        self.QA_actionOpen = QAction(MainWindow)
        self.QA_actionOpen.setObjectName(u"QA_actionOpen")
        self.QA_actionNew = QAction(MainWindow)
        self.QA_actionNew.setObjectName(u"QA_actionNew")
        self.QA_actionSave = QAction(MainWindow)
        self.QA_actionSave.setObjectName(u"QA_actionSave")
        self.QA_actionSave_as = QAction(MainWindow)
        self.QA_actionSave_as.setObjectName(u"QA_actionSave_as")
        self.QA_actionPrint = QAction(MainWindow)
        self.QA_actionPrint.setObjectName(u"QA_actionPrint")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 10, 391, 221))
        self.QL_label_address = QLabel(self.widget)
        self.QL_label_address.setObjectName(u"QL_label_address")
        self.QL_label_address.setGeometry(QRect(16, 124, 51, 21))
        font = QFont()
        font.setPointSize(10)
        self.QL_label_address.setFont(font)
        self.QL_label_num_phone = QLabel(self.widget)
        self.QL_label_num_phone.setObjectName(u"QL_label_num_phone")
        self.QL_label_num_phone.setGeometry(QRect(16, 93, 31, 21))
        self.QL_label_num_phone.setFont(font)
        self.QL_label_name = QLabel(self.widget)
        self.QL_label_name.setObjectName(u"QL_label_name")
        self.QL_label_name.setGeometry(QRect(16, 0, 117, 21))
        self.QL_label_name.setFont(font)
        self.QL_label_lices_num = QLabel(self.widget)
        self.QL_label_lices_num.setObjectName(u"QL_label_lices_num")
        self.QL_label_lices_num.setGeometry(QRect(16, 62, 55, 21))
        self.QL_label_lices_num.setFont(font)
        self.QL_label_date_fix = QLabel(self.widget)
        self.QL_label_date_fix.setObjectName(u"QL_label_date_fix")
        self.QL_label_date_fix.setGeometry(QRect(16, 155, 110, 21))
        self.QL_label_date_fix.setFont(font)
        self.QL_label_num_vin = QLabel(self.widget)
        self.QL_label_num_vin.setObjectName(u"QL_label_num_vin")
        self.QL_label_num_vin.setGeometry(QRect(16, 31, 54, 21))
        self.QL_label_num_vin.setFont(font)
        self.QL_label_date_fix_2 = QLabel(self.widget)
        self.QL_label_date_fix_2.setObjectName(u"QL_label_date_fix_2")
        self.QL_label_date_fix_2.setGeometry(QRect(15, 189, 110, 21))
        self.QL_label_date_fix_2.setFont(font)
        self.TE_t_name = QTextEdit(self.widget)
        self.TE_t_name.setObjectName(u"TE_t_name")
        self.TE_t_name.setGeometry(QRect(141, 1, 239, 24))
        self.TE_t_vin_num = QTextEdit(self.widget)
        self.TE_t_vin_num.setObjectName(u"TE_t_vin_num")
        self.TE_t_vin_num.setGeometry(QRect(141, 32, 239, 24))
        self.TE_t_lices_num = QTextEdit(self.widget)
        self.TE_t_lices_num.setObjectName(u"TE_t_lices_num")
        self.TE_t_lices_num.setGeometry(QRect(141, 63, 239, 24))
        self.TE_t_num_phone = QTextEdit(self.widget)
        self.TE_t_num_phone.setObjectName(u"TE_t_num_phone")
        self.TE_t_num_phone.setGeometry(QRect(141, 94, 239, 24))
        self.TE_t_address = QTextEdit(self.widget)
        self.TE_t_address.setObjectName(u"TE_t_address")
        self.TE_t_address.setGeometry(QRect(141, 125, 239, 24))
        self.TE_t_date = QTextEdit(self.widget)
        self.TE_t_date.setObjectName(u"TE_t_date")
        self.TE_t_date.setGeometry(QRect(141, 156, 239, 24))
        self.TE_t_fix = QTextEdit(self.widget)
        self.TE_t_fix.setObjectName(u"TE_t_fix")
        self.TE_t_fix.setGeometry(QRect(141, 187, 239, 23))
        self.widget_grap = QWidget(self.centralwidget)
        self.widget_grap.setObjectName(u"widget_grap")
        self.widget_grap.setGeometry(QRect(10, 290, 391, 271))
        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(410, 270, 381, 281))
        self.QL_label = QLabel(self.widget_2)
        self.QL_label.setObjectName(u"QL_label")
        self.QL_label.setGeometry(QRect(10, 10, 81, 21))
        self.QL_label.setFont(font)
        self.TE_t_comment = QTextEdit(self.widget_2)
        self.TE_t_comment.setObjectName(u"TE_t_comment")
        self.TE_t_comment.setGeometry(QRect(10, 40, 361, 241))
        self.widget_4 = QWidget(self.centralwidget)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(270, 560, 271, 41))
        self.PB_b_cancel = QPushButton(self.widget_4)
        self.PB_b_cancel.setObjectName(u"PB_b_cancel")
        self.PB_b_cancel.setGeometry(QRect(140, 10, 93, 28))
        font1 = QFont()
        font1.setBold(True)
        font1.setWeight(75)
        self.PB_b_cancel.setFont(font1)
        self.PB_b_search = QPushButton(self.widget_4)
        self.PB_b_search.setObjectName(u"PB_b_search")
        self.PB_b_search.setGeometry(QRect(40, 10, 93, 28))
        self.PB_b_search.setFont(font1)
        self.grap = QTabWidget(self.centralwidget)
        self.grap.setObjectName(u"grap")
        self.grap.setGeometry(QRect(20, 240, 371, 321))
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.GV_graphicsView = QGraphicsView(self.tab_1)
        self.GV_graphicsView.setObjectName(u"GV_graphicsView")
        self.GV_graphicsView.setGeometry(QRect(0, 10, 361, 281))
        self.grap.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.GV_graphicsView_2 = QGraphicsView(self.tab_2)
        self.GV_graphicsView_2.setObjectName(u"GV_graphicsView_2")
        self.GV_graphicsView_2.setGeometry(QRect(0, 10, 361, 281))
        self.grap.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.GV_graphicsView_3 = QGraphicsView(self.tab_3)
        self.GV_graphicsView_3.setObjectName(u"GV_graphicsView_3")
        self.GV_graphicsView_3.setGeometry(QRect(0, 10, 361, 281))
        self.grap.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.GV_graphicsView_4 = QGraphicsView(self.tab_4)
        self.GV_graphicsView_4.setObjectName(u"GV_graphicsView_4")
        self.GV_graphicsView_4.setGeometry(QRect(0, 10, 361, 281))
        self.grap.addTab(self.tab_4, "")
        self.widget_vin_num = QWidget(self.centralwidget)
        self.widget_vin_num.setObjectName(u"widget_vin_num")
        self.widget_vin_num.setGeometry(QRect(410, 10, 381, 251))
        self.TE_t_name_2 = QTextEdit(self.widget_vin_num)
        self.TE_t_name_2.setObjectName(u"TE_t_name_2")
        self.TE_t_name_2.setGeometry(QRect(130, 10, 241, 24))
        self.QL_label_contry = QLabel(self.widget_vin_num)
        self.QL_label_contry.setObjectName(u"QL_label_contry")
        self.QL_label_contry.setGeometry(QRect(10, 10, 117, 21))
        self.QL_label_contry.setFont(font)
        self.TE_t_name_3 = QTextEdit(self.widget_vin_num)
        self.TE_t_name_3.setObjectName(u"TE_t_name_3")
        self.TE_t_name_3.setGeometry(QRect(130, 40, 241, 24))
        self.QL_label_branch = QLabel(self.widget_vin_num)
        self.QL_label_branch.setObjectName(u"QL_label_branch")
        self.QL_label_branch.setGeometry(QRect(10, 40, 117, 21))
        self.QL_label_branch.setFont(font)
        self.QL_label_car = QLabel(self.widget_vin_num)
        self.QL_label_car.setObjectName(u"QL_label_car")
        self.QL_label_car.setGeometry(QRect(10, 70, 117, 21))
        self.QL_label_car.setFont(font)
        self.TE_t_name_4 = QTextEdit(self.widget_vin_num)
        self.TE_t_name_4.setObjectName(u"TE_t_name_4")
        self.TE_t_name_4.setGeometry(QRect(130, 70, 241, 24))
        self.QL_label_name_car = QLabel(self.widget_vin_num)
        self.QL_label_name_car.setObjectName(u"QL_label_name_car")
        self.QL_label_name_car.setGeometry(QRect(10, 100, 117, 21))
        self.QL_label_name_car.setFont(font)
        self.TE_t_name_5 = QTextEdit(self.widget_vin_num)
        self.TE_t_name_5.setObjectName(u"TE_t_name_5")
        self.TE_t_name_5.setGeometry(QRect(130, 100, 241, 24))
        self.TE_t_name_6 = QTextEdit(self.widget_vin_num)
        self.TE_t_name_6.setObjectName(u"TE_t_name_6")
        self.TE_t_name_6.setGeometry(QRect(130, 130, 241, 24))
        self.QL_label_sec_num = QLabel(self.widget_vin_num)
        self.QL_label_sec_num.setObjectName(u"QL_label_sec_num")
        self.QL_label_sec_num.setGeometry(QRect(10, 130, 117, 21))
        self.QL_label_sec_num.setFont(font)
        self.TE_t_name_7 = QTextEdit(self.widget_vin_num)
        self.TE_t_name_7.setObjectName(u"TE_t_name_7")
        self.TE_t_name_7.setGeometry(QRect(130, 160, 241, 24))
        self.QL_label_prod_date = QLabel(self.widget_vin_num)
        self.QL_label_prod_date.setObjectName(u"QL_label_prod_date")
        self.QL_label_prod_date.setGeometry(QRect(10, 160, 117, 21))
        self.QL_label_prod_date.setFont(font)
        self.QL_label_factor = QLabel(self.widget_vin_num)
        self.QL_label_factor.setObjectName(u"QL_label_factor")
        self.QL_label_factor.setGeometry(QRect(10, 190, 131, 21))
        font2 = QFont()
        font2.setPointSize(9)
        self.QL_label_factor.setFont(font2)
        self.TE_t_name_8 = QTextEdit(self.widget_vin_num)
        self.TE_t_name_8.setObjectName(u"TE_t_name_8")
        self.TE_t_name_8.setGeometry(QRect(130, 190, 241, 24))
        self.QL_label_num = QLabel(self.widget_vin_num)
        self.QL_label_num.setObjectName(u"QL_label_num")
        self.QL_label_num.setGeometry(QRect(10, 220, 117, 21))
        font3 = QFont()
        font3.setPointSize(8)
        self.QL_label_num.setFont(font3)
        self.TE_t_name_9 = QTextEdit(self.widget_vin_num)
        self.TE_t_name_9.setObjectName(u"TE_t_name_9")
        self.TE_t_name_9.setGeometry(QRect(130, 220, 241, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 796, 26))
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuEdit.addAction(self.QA_actionOpen)
        self.menuEdit.addAction(self.QA_actionNew)
        self.menuEdit.addAction(self.QA_actionSave)
        self.menuEdit.addAction(self.QA_actionSave_as)
        self.menuEdit.addAction(self.QA_actionPrint)

        self.retranslateUi(MainWindow)

        self.grap.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.QA_actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.QA_actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.QA_actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.QA_actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as", None))
        self.QA_actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print", None))
        self.QL_label_address.setText(QCoreApplication.translate("MainWindow", u"\u0110\u1ecba ch\u1ec9", None))
        self.QL_label_num_phone.setText(QCoreApplication.translate("MainWindow", u"S\u0110T", None))
        self.QL_label_name.setText(QCoreApplication.translate("MainWindow", u"T\u00ean kh\u00e1ch h\u00e0ng", None))
        self.QL_label_lices_num.setText(QCoreApplication.translate("MainWindow", u"Bi\u1ec3n s\u1ed1", None))
        self.QL_label_date_fix.setText(QCoreApplication.translate("MainWindow", u"Ng\u00e0y s\u1eeda ch\u1eefa", None))
        self.QL_label_num_vin.setText(QCoreApplication.translate("MainWindow", u"M\u00e3 VIN", None))
        self.QL_label_date_fix_2.setText(QCoreApplication.translate("MainWindow", u"L\u1ed7i xe", None))
        self.QL_label.setText(QCoreApplication.translate("MainWindow", u"Ch\u1ea9n \u0111o\u00e1n", None))
        self.PB_b_cancel.setText(QCoreApplication.translate("MainWindow", u"Tho\u00e1t", None))
        self.PB_b_search.setText(QCoreApplication.translate("MainWindow", u"T\u00ecm ki\u1ebfm", None))
        self.grap.setTabText(self.grap.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Xylanh 1", None))
        self.grap.setTabText(self.grap.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Xylanh 2", None))
        self.grap.setTabText(self.grap.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Xylanh 3", None))
        self.grap.setTabText(self.grap.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Xylanh 4", None))
        self.QL_label_contry.setText(QCoreApplication.translate("MainWindow", u"N\u01b0\u1edbc s\u1ea3n xu\u1ea5t", None))
        self.QL_label_branch.setText(QCoreApplication.translate("MainWindow", u"D\u00f2ng xe", None))
        self.QL_label_car.setText(QCoreApplication.translate("MainWindow", u"M\u1eabu xe", None))
        self.QL_label_name_car.setText(QCoreApplication.translate("MainWindow", u"D\u00f2ng xe", None))
        self.QL_label_sec_num.setText(QCoreApplication.translate("MainWindow", u"M\u00e3 b\u1ea3o m\u1eadt", None))
        self.QL_label_prod_date.setText(QCoreApplication.translate("MainWindow", u"N\u0103m s\u1ea3n xu\u1ea5t", None))
        self.QL_label_factor.setText(QCoreApplication.translate("MainWindow", u"Nh\u00e0 m\u00e1y l\u1eafp r\u00e1p", None))
        self.QL_label_num.setText(QCoreApplication.translate("MainWindow", u"S\u1ed1 th\u1ee9 t\u1ef1 s\u1ea3n xu\u1ea5t", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

