# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUIinput.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1173, 796)
        self.QA_actionOpen = QAction(MainWindow)
        self.QA_actionOpen.setObjectName(u"QA_actionOpen")
        self.QA_actionNew = QAction(MainWindow)
        self.QA_actionNew.setObjectName(u"QA_actionNew")
        self.QA_actionSave = QAction(MainWindow)
        self.QA_actionSave.setObjectName(u"QA_actionSave")
        self.QA_actionSave_as = QAction(MainWindow)
        self.QA_actionSave_as.setObjectName(u"QA_actionSave_as")
        self.QA_actionGraphics_car = QAction(MainWindow)
        self.QA_actionGraphics_car.setObjectName(u"QA_actionGraphics_car")
        self.QA_actionDate = QAction(MainWindow)
        self.QA_actionDate.setObjectName(u"QA_actionDate")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(0, 0, 0, 0))
        self.splitter.setOrientation(Qt.Horizontal)
        self.splitter_2 = QSplitter(self.centralwidget)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(0, 0, 0, 0))
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(0, 0, 2, 2))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(0, 0, 2, 2))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.splitter_3 = QSplitter(self.centralwidget)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(0, 0, 0, 0))
        self.splitter_3.setOrientation(Qt.Vertical)
        self.layoutWidget2 = QWidget(self.centralwidget)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(0, 0, 2, 2))
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.splitter_4 = QSplitter(self.centralwidget)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setGeometry(QRect(0, 0, 0, 0))
        self.splitter_4.setOrientation(Qt.Vertical)
        self.GB_incident_phenomena = QGroupBox(self.centralwidget)
        self.GB_incident_phenomena.setObjectName(u"GB_incident_phenomena")
        self.GB_incident_phenomena.setGeometry(QRect(20, 350, 411, 371))
        font = QFont()
        font.setPointSize(14)
        self.GB_incident_phenomena.setFont(font)
        self.GB_incident_phenomena.setFlat(False)
        self.GB_incident_phenomena.setCheckable(False)
        self.CB_incident_1 = QCheckBox(self.GB_incident_phenomena)
        self.CB_incident_1.setObjectName(u"CB_incident_1")
        self.CB_incident_1.setGeometry(QRect(10, 50, 381, 21))
        font1 = QFont()
        font1.setPointSize(11)
        self.CB_incident_1.setFont(font1)
        self.CB_incident_2 = QCheckBox(self.GB_incident_phenomena)
        self.CB_incident_2.setObjectName(u"CB_incident_2")
        self.CB_incident_2.setGeometry(QRect(10, 80, 381, 21))
        self.CB_incident_2.setFont(font1)
        self.CB_incident_3 = QCheckBox(self.GB_incident_phenomena)
        self.CB_incident_3.setObjectName(u"CB_incident_3")
        self.CB_incident_3.setGeometry(QRect(10, 110, 381, 21))
        self.CB_incident_3.setFont(font1)
        self.CB_incident_4 = QCheckBox(self.GB_incident_phenomena)
        self.CB_incident_4.setObjectName(u"CB_incident_4")
        self.CB_incident_4.setGeometry(QRect(10, 140, 381, 21))
        self.CB_incident_4.setFont(font1)
        self.CB_incident_5 = QCheckBox(self.GB_incident_phenomena)
        self.CB_incident_5.setObjectName(u"CB_incident_5")
        self.CB_incident_5.setGeometry(QRect(10, 170, 381, 21))
        self.CB_incident_5.setFont(font1)
        self.CB_incident_6 = QCheckBox(self.GB_incident_phenomena)
        self.CB_incident_6.setObjectName(u"CB_incident_6")
        self.CB_incident_6.setGeometry(QRect(10, 200, 381, 21))
        self.CB_incident_6.setFont(font1)
        self.CB_incident_8 = QCheckBox(self.GB_incident_phenomena)
        self.CB_incident_8.setObjectName(u"CB_incident_8")
        self.CB_incident_8.setGeometry(QRect(10, 260, 381, 21))
        self.CB_incident_8.setFont(font1)
        self.CB_incident_7 = QCheckBox(self.GB_incident_phenomena)
        self.CB_incident_7.setObjectName(u"CB_incident_7")
        self.CB_incident_7.setGeometry(QRect(10, 230, 381, 21))
        self.CB_incident_7.setFont(font1)
        self.CB_incident_9 = QCheckBox(self.GB_incident_phenomena)
        self.CB_incident_9.setObjectName(u"CB_incident_9")
        self.CB_incident_9.setGeometry(QRect(10, 290, 381, 21))
        self.CB_incident_9.setFont(font1)
        self.Label_incident_phenomena_warning = QLabel(self.GB_incident_phenomena)
        self.Label_incident_phenomena_warning.setObjectName(u"Label_incident_phenomena_warning")
        self.Label_incident_phenomena_warning.setGeometry(QRect(60, 330, 291, 31))
        font2 = QFont()
        font2.setPointSize(12)
        self.Label_incident_phenomena_warning.setFont(font2)
        self.Label_incident_phenomena_warning.setTextInteractionFlags(Qt.NoTextInteraction)
        self.GB_customer_information = QGroupBox(self.centralwidget)
        self.GB_customer_information.setObjectName(u"GB_customer_information")
        self.GB_customer_information.setGeometry(QRect(20, 20, 411, 321))
        self.GB_customer_information.setFont(font)
        self.GB_customer_information.setMouseTracking(False)
        self.Label_customer_information_warning = QLabel(self.GB_customer_information)
        self.Label_customer_information_warning.setObjectName(u"Label_customer_information_warning")
        self.Label_customer_information_warning.setGeometry(QRect(60, 280, 291, 31))
        self.Label_customer_information_warning.setFont(font2)
        self.Label_customer_information_warning.setTextInteractionFlags(Qt.NoTextInteraction)
        self.label_customer_name = QLabel(self.GB_customer_information)
        self.label_customer_name.setObjectName(u"label_customer_name")
        self.label_customer_name.setGeometry(QRect(3, 34, 117, 21))
        font3 = QFont()
        font3.setPointSize(10)
        self.label_customer_name.setFont(font3)
        self.label_VIN_code = QLabel(self.GB_customer_information)
        self.label_VIN_code.setObjectName(u"label_VIN_code")
        self.label_VIN_code.setGeometry(QRect(3, 73, 54, 21))
        self.label_VIN_code.setFont(font3)
        self.label_number_plate = QLabel(self.GB_customer_information)
        self.label_number_plate.setObjectName(u"label_number_plate")
        self.label_number_plate.setGeometry(QRect(3, 113, 55, 21))
        self.label_number_plate.setFont(font3)
        self.label_phone_number = QLabel(self.GB_customer_information)
        self.label_phone_number.setObjectName(u"label_phone_number")
        self.label_phone_number.setGeometry(QRect(3, 152, 31, 21))
        self.label_phone_number.setFont(font3)
        self.label_address = QLabel(self.GB_customer_information)
        self.label_address.setObjectName(u"label_address")
        self.label_address.setGeometry(QRect(3, 191, 51, 21))
        self.label_address.setFont(font3)
        self.label_fixing_date = QLabel(self.GB_customer_information)
        self.label_fixing_date.setObjectName(u"label_fixing_date")
        self.label_fixing_date.setGeometry(QRect(3, 231, 110, 21))
        self.label_fixing_date.setFont(font3)
        self.LE_customer_name = QLineEdit(self.GB_customer_information)
        self.LE_customer_name.setObjectName(u"LE_customer_name")
        self.LE_customer_name.setGeometry(QRect(128, 39, 271, 27))
        self.LE_customer_name.setFont(font3)
#if QT_CONFIG(whatsthis)
        self.LE_customer_name.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.LE_customer_name.setAutoFillBackground(False)
        self.LE_customer_name.setClearButtonEnabled(True)
        self.LE_VIN_code = QLineEdit(self.GB_customer_information)
        self.LE_VIN_code.setObjectName(u"LE_VIN_code")
        self.LE_VIN_code.setGeometry(QRect(128, 78, 271, 27))
        self.LE_VIN_code.setFont(font3)
        self.LE_VIN_code.setClearButtonEnabled(True)
        self.LE_number_plate = QLineEdit(self.GB_customer_information)
        self.LE_number_plate.setObjectName(u"LE_number_plate")
        self.LE_number_plate.setGeometry(QRect(128, 117, 271, 27))
        self.LE_number_plate.setFont(font3)
        self.LE_number_plate.setClearButtonEnabled(True)
        self.LE_phone_number = QLineEdit(self.GB_customer_information)
        self.LE_phone_number.setObjectName(u"LE_phone_number")
        self.LE_phone_number.setGeometry(QRect(128, 156, 271, 27))
        self.LE_phone_number.setFont(font3)
        self.LE_phone_number.setClearButtonEnabled(True)
        self.LE_address = QLineEdit(self.GB_customer_information)
        self.LE_address.setObjectName(u"LE_address")
        self.LE_address.setGeometry(QRect(128, 195, 271, 27))
        self.LE_address.setFont(font3)
        self.LE_address.setClearButtonEnabled(True)
        self.DE_fixing_date = QDateEdit(self.GB_customer_information)
        self.DE_fixing_date.setObjectName(u"DE_fixing_date")
        self.DE_fixing_date.setGeometry(QRect(128, 234, 113, 27))
        self.DE_fixing_date.setFont(font3)
        self.GB_incident_images = QGroupBox(self.centralwidget)
        self.GB_incident_images.setObjectName(u"GB_incident_images")
        self.GB_incident_images.setGeometry(QRect(440, 20, 721, 651))
        self.GB_incident_images.setFont(font)
        self.GV_inciden_images = QGraphicsView(self.GB_incident_images)
        self.GV_inciden_images.setObjectName(u"GV_inciden_images")
        self.GV_inciden_images.setGeometry(QRect(10, 39, 701, 591))
        self.GV_inciden_images.setAutoFillBackground(True)
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.NoBrush)
        self.GV_inciden_images.setBackgroundBrush(brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.NoBrush)
        self.GV_inciden_images.setForegroundBrush(brush1)
        self.GV_inciden_images.setDragMode(QGraphicsView.NoDrag)
        self.QL_label_3 = QLabel(self.centralwidget)
        self.QL_label_3.setObjectName(u"QL_label_3")
        self.QL_label_3.setGeometry(QRect(240, 710, 55, 16))
        self.BT_confirm = QPushButton(self.centralwidget)
        self.BT_confirm.setObjectName(u"BT_confirm")
        self.BT_confirm.setGeometry(QRect(720, 690, 93, 28))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.BT_confirm.setFont(font4)
        self.BT_exit = QPushButton(self.centralwidget)
        self.BT_exit.setObjectName(u"BT_exit")
        self.BT_exit.setGeometry(QRect(820, 690, 93, 28))
        self.BT_exit.setFont(font4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.GB_incident_phenomena.raise_()
        self.GB_incident_images.raise_()
        self.splitter.raise_()
        self.splitter_2.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.splitter_3.raise_()
        self.layoutWidget.raise_()
        self.splitter_4.raise_()
        self.GB_customer_information.raise_()
        self.QL_label_3.raise_()
        self.BT_confirm.raise_()
        self.BT_exit.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1173, 26))
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuEdit.addAction(self.QA_actionOpen)
        self.menuEdit.addAction(self.QA_actionNew)
        self.menuEdit.addAction(self.QA_actionSave)
        self.menuEdit.addAction(self.QA_actionSave_as)
        self.menuView.addAction(self.QA_actionGraphics_car)
        self.menuView.addAction(self.QA_actionDate)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"GUI_input", None))
        self.QA_actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.QA_actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.QA_actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.QA_actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as", None))
        self.QA_actionGraphics_car.setText(QCoreApplication.translate("MainWindow", u"Graphics car", None))
        self.QA_actionDate.setText(QCoreApplication.translate("MainWindow", u"Date ", None))
        self.GB_incident_phenomena.setTitle(QCoreApplication.translate("MainWindow", u"S\u1ef1 c\u1ed1 c\u1ee7a xe", None))
        self.CB_incident_1.setText(QCoreApplication.translate("MainWindow", u"Xe \u0111\u1ed9t ng\u1ed9t t\u1eaft m\u00e1y gi\u1eefa \u0111\u01b0\u1eddng", None))
        self.CB_incident_2.setText(QCoreApplication.translate("MainWindow", u"Kh\u00f3 \u0111\u1ec1 m\u00e1y khi kh\u1edfi \u0111\u1ed9ng", None))
        self.CB_incident_3.setText(QCoreApplication.translate("MainWindow", u"Th\u1ea5y nhi\u1ec1u kh\u00f3i \u0111en t\u1ecfa ra khi t\u0103ng t\u1ed1c", None))
        self.CB_incident_4.setText(QCoreApplication.translate("MainWindow", u"C\u1ea3m gi\u00e1c xe \u0111\u00ec khi leo d\u1ed1c", None))
        self.CB_incident_5.setText(QCoreApplication.translate("MainWindow", u"Xe \u0111\u1ed9t ng\u1ed9t gi\u1ea3m v\u00f2ng tua khi t\u0103ng t\u1ed1c", None))
        self.CB_incident_6.setText(QCoreApplication.translate("MainWindow", u"C\u00f3 ti\u1ebfng \u0111\u1ed9ng l\u1ea1 \u1edf \u0111\u1ed9ng c\u01a1", None))
        self.CB_incident_8.setText(QCoreApplication.translate("MainWindow", u"V\u00f2ng tua kh\u00f4ng \u0111\u00e1p \u1ee9ng ngay khi t\u0103ng ", None))
        self.CB_incident_7.setText(QCoreApplication.translate("MainWindow", u"C\u1ea3m gi\u00e1c l\u00e1i b\u1ea5t th\u01b0\u1eddng, kh\u00f3 ki\u1ec3m so\u00e1t", None))
        self.CB_incident_9.setText(QCoreApplication.translate("MainWindow", u"\u0110\u1ed9ng c\u01a1 rung l\u1eafc m\u1ea1nh khi v\u1eadn h\u00e0nh", None))
        self.Label_incident_phenomena_warning.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#ff0000;\">Vui l\u00f2ng ch\u1ecdn s\u1ef1 c\u1ed1 c\u1ee7a xe</span></p></body></html>", None))
        self.GB_customer_information.setTitle(QCoreApplication.translate("MainWindow", u"Th\u00f4ng tin kh\u00e1ch h\u00e0ng", None))
        self.Label_customer_information_warning.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#ff0000;\">Vui l\u00f2ng nh\u1eadp \u0111\u1ea7y \u0111\u1ee7 th\u00f4ng tin</span></p></body></html>", None))
        self.label_customer_name.setText(QCoreApplication.translate("MainWindow", u"T\u00ean kh\u00e1ch h\u00e0ng", None))
        self.label_VIN_code.setText(QCoreApplication.translate("MainWindow", u"M\u00e3 VIN", None))
        self.label_number_plate.setText(QCoreApplication.translate("MainWindow", u"Bi\u1ec3n s\u1ed1", None))
        self.label_phone_number.setText(QCoreApplication.translate("MainWindow", u"S\u0110T", None))
        self.label_address.setText(QCoreApplication.translate("MainWindow", u"\u0110\u1ecba ch\u1ec9", None))
        self.label_fixing_date.setText(QCoreApplication.translate("MainWindow", u"Ng\u00e0y s\u1eeda ch\u1eefa", None))
        self.LE_customer_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Vui l\u00f2ng nh\u1eadp t\u00ean c\u1ee7a b\u1ea1n", None))
        self.LE_VIN_code.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nh\u1eadp m\u00e3 VIN", None))
        self.LE_number_plate.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Bi\u1ec3n s\u1ed1 xe c\u1ea7n ki\u1ec3m tra", None))
        self.LE_phone_number.setPlaceholderText(QCoreApplication.translate("MainWindow", u"S\u1ed1 \u0111i\u1ec7n tho\u1ea1i li\u00ean l\u1ea1c", None))
        self.LE_address.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nh\u1eadp \u0111\u1ecba ch\u1ec9 nh\u00e0 c\u1ee7a b\u1ea1n", None))
        self.DE_fixing_date.setSpecialValueText("")
        self.GB_incident_images.setTitle(QCoreApplication.translate("MainWindow", u"H\u00ecnh \u1ea3nh s\u1ef1 c\u1ed1", None))
        self.QL_label_3.setText("")
        self.BT_confirm.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.BT_exit.setText(QCoreApplication.translate("MainWindow", u"Tho\u00e1t", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

