# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUImain.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 798)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionOpen_2 = QAction(MainWindow)
        self.actionOpen_2.setObjectName(u"actionOpen_2")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(MainWindow)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.GB_caculate = QGroupBox(self.centralwidget)
        self.GB_caculate.setObjectName(u"GB_caculate")
        self.GB_caculate.setGeometry(QRect(10, 10, 381, 411))
        font = QFont()
        font.setPointSize(12)
        self.GB_caculate.setFont(font)
        self.l_xup_cor = QLineEdit(self.GB_caculate)
        self.l_xup_cor.setObjectName(u"l_xup_cor")
        self.l_xup_cor.setGeometry(QRect(191, 180, 178, 24))
        font1 = QFont()
        font1.setPointSize(10)
        self.l_xup_cor.setFont(font1)
        self.label_piston_jour = QLabel(self.GB_caculate)
        self.label_piston_jour.setObjectName(u"label_piston_jour")
        self.label_piston_jour.setGeometry(QRect(10, 87, 141, 21))
        self.label_piston_jour.setFont(font1)
        self.label_comp_rat = QLabel(self.GB_caculate)
        self.label_comp_rat.setObjectName(u"label_comp_rat")
        self.label_comp_rat.setGeometry(QRect(10, 56, 72, 21))
        self.label_comp_rat.setFont(font1)
        self.l_cyl_dm = QLineEdit(self.GB_caculate)
        self.l_cyl_dm.setObjectName(u"l_cyl_dm")
        self.l_cyl_dm.setGeometry(QRect(191, 118, 178, 24))
        self.l_cyl_dm.setFont(font1)
        self.label_cyl_dm = QLabel(self.GB_caculate)
        self.label_cyl_dm.setObjectName(u"label_cyl_dm")
        self.label_cyl_dm.setGeometry(QRect(10, 118, 136, 21))
        self.label_cyl_dm.setFont(font1)
        self.l_air_press = QLineEdit(self.GB_caculate)
        self.l_air_press.setObjectName(u"l_air_press")
        self.l_air_press.setGeometry(QRect(191, 211, 178, 23))
        self.l_air_press.setFont(font1)
        self.l_extTem = QLineEdit(self.GB_caculate)
        self.l_extTem.setObjectName(u"l_extTem")
        self.l_extTem.setGeometry(QRect(191, 25, 178, 24))
        self.l_extTem.setFont(font1)
        self.l_piston_jour = QLineEdit(self.GB_caculate)
        self.l_piston_jour.setObjectName(u"l_piston_jour")
        self.l_piston_jour.setGeometry(QRect(191, 87, 178, 24))
        self.l_piston_jour.setFont(font1)
        self.l_rod_len = QLineEdit(self.GB_caculate)
        self.l_rod_len.setObjectName(u"l_rod_len")
        self.l_rod_len.setGeometry(QRect(191, 149, 178, 24))
        self.l_rod_len.setFont(font1)
        self.label_extTem = QLabel(self.GB_caculate)
        self.label_extTem.setObjectName(u"label_extTem")
        self.label_extTem.setGeometry(QRect(10, 25, 63, 21))
        self.label_extTem.setFont(font1)
        self.label_rod_len = QLabel(self.GB_caculate)
        self.label_rod_len.setObjectName(u"label_rod_len")
        self.label_rod_len.setGeometry(QRect(10, 149, 167, 21))
        self.label_rod_len.setFont(font1)
        self.label_air_press = QLabel(self.GB_caculate)
        self.label_air_press.setObjectName(u"label_air_press")
        self.label_air_press.setGeometry(QRect(10, 211, 115, 21))
        self.label_air_press.setFont(font1)
        self.l_comp_rat = QLineEdit(self.GB_caculate)
        self.l_comp_rat.setObjectName(u"l_comp_rat")
        self.l_comp_rat.setGeometry(QRect(191, 56, 178, 24))
        self.l_comp_rat.setFont(font1)
        self.label_xup_cor = QLabel(self.GB_caculate)
        self.label_xup_cor.setObjectName(u"label_xup_cor")
        self.label_xup_cor.setGeometry(QRect(10, 180, 174, 21))
        self.label_xup_cor.setFont(font1)
        self.b_clear = QPushButton(self.GB_caculate)
        self.b_clear.setObjectName(u"b_clear")
        self.b_clear.setGeometry(QRect(170, 240, 93, 28))
        font2 = QFont()
        font2.setPointSize(8)
        self.b_clear.setFont(font2)
        self.b_math = QPushButton(self.GB_caculate)
        self.b_math.setObjectName(u"b_math")
        self.b_math.setGeometry(QRect(70, 240, 93, 28))
        self.b_math.setFont(font2)
        self.label_Comp_temp_F = QLabel(self.GB_caculate)
        self.label_Comp_temp_F.setObjectName(u"label_Comp_temp_F")
        self.label_Comp_temp_F.setGeometry(QRect(10, 335, 115, 21))
        self.label_Comp_temp_F.setFont(font1)
        self.t_watt = QTextBrowser(self.GB_caculate)
        self.t_watt.setObjectName(u"t_watt")
        self.t_watt.setGeometry(QRect(170, 370, 201, 22))
        self.label_Compression = QLabel(self.GB_caculate)
        self.label_Compression.setObjectName(u"label_Compression")
        self.label_Compression.setGeometry(QRect(10, 277, 89, 21))
        self.label_Compression.setFont(font1)
        self.label_Comp_temp_C = QLabel(self.GB_caculate)
        self.label_Comp_temp_C.setObjectName(u"label_Comp_temp_C")
        self.label_Comp_temp_C.setGeometry(QRect(10, 306, 116, 21))
        self.label_Comp_temp_C.setFont(font1)
        self.t_Comp_temp_C = QTextBrowser(self.GB_caculate)
        self.t_Comp_temp_C.setObjectName(u"t_Comp_temp_C")
        self.t_Comp_temp_C.setGeometry(QRect(170, 312, 201, 22))
        self.t_Comp_temp_F = QTextBrowser(self.GB_caculate)
        self.t_Comp_temp_F.setObjectName(u"t_Comp_temp_F")
        self.t_Comp_temp_F.setGeometry(QRect(170, 341, 201, 22))
        self.label_watt = QLabel(self.GB_caculate)
        self.label_watt.setObjectName(u"label_watt")
        self.label_watt.setGeometry(QRect(10, 364, 69, 21))
        self.label_watt.setFont(font1)
        self.t_Compression = QTextBrowser(self.GB_caculate)
        self.t_Compression.setObjectName(u"t_Compression")
        self.t_Compression.setGeometry(QRect(170, 283, 201, 22))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 430, 381, 261))
        self.groupBox_2.setFont(font)
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 40, 128, 24))
        self.label_16.setFont(font1)
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 142, 87, 21))
        self.label_13.setFont(font1)
        self.progressBar_3 = QProgressBar(self.groupBox_2)
        self.progressBar_3.setObjectName(u"progressBar_3")
        self.progressBar_3.setGeometry(QRect(140, 222, 118, 23))
        self.progressBar_3.setValue(24)
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 105, 87, 21))
        self.label_12.setFont(font1)
        self.progressBar = QProgressBar(self.groupBox_2)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(140, 102, 118, 23))
        self.progressBar.setValue(24)
        self.progressBar_4 = QProgressBar(self.groupBox_2)
        self.progressBar_4.setObjectName(u"progressBar_4")
        self.progressBar_4.setGeometry(QRect(140, 182, 118, 23))
        self.progressBar_4.setValue(24)
        self.pushButton_4 = QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(280, 142, 93, 28))
        self.pushButton_4.setFont(font2)
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 216, 87, 21))
        self.label_15.setFont(font1)
        self.pushButton_5 = QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(280, 182, 93, 28))
        self.pushButton_5.setFont(font2)
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(250, 40, 31, 24))
        self.label_17.setFont(font1)
        self.progressBar_2 = QProgressBar(self.groupBox_2)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(140, 142, 118, 23))
        self.progressBar_2.setValue(24)
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(30, 179, 87, 21))
        self.label_14.setFont(font1)
        self.pushButton_3 = QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(280, 102, 93, 28))
        self.pushButton_3.setFont(font2)
        self.doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(164, 40, 80, 24))
        self.doubleSpinBox.setFont(font2)
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setValue(99.989999999999995)
        self.pushButton_6 = QPushButton(self.groupBox_2)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(280, 220, 93, 28))
        self.pushButton_6.setFont(font2)
        self.GB_Table = QGroupBox(self.centralwidget)
        self.GB_Table.setObjectName(u"GB_Table")
        self.GB_Table.setGeometry(QRect(400, 20, 691, 311))
        self.GB_Table.setFont(font)
        self.tableWidget = QTableWidget(self.GB_Table)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 30, 681, 271))
        self.b_cancel = QPushButton(self.centralwidget)
        self.b_cancel.setObjectName(u"b_cancel")
        self.b_cancel.setGeometry(QRect(930, 710, 93, 28))
        font3 = QFont()
        font3.setBold(True)
        font3.setWeight(75)
        self.b_cancel.setFont(font3)
        self.b_confirm = QPushButton(self.centralwidget)
        self.b_confirm.setObjectName(u"b_confirm")
        self.b_confirm.setGeometry(QRect(830, 710, 93, 28))
        self.b_confirm.setFont(font3)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(400, 330, 691, 361))
        self.groupBox_3.setFont(font)
        self.grap = QTabWidget(self.groupBox_3)
        self.grap.setObjectName(u"grap")
        self.grap.setGeometry(QRect(20, 30, 661, 321))
        self.grap.setFont(font1)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.graphicsView = QGraphicsView(self.tab_1)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(0, 10, 641, 271))
        self.grap.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.graphicsView_2 = QGraphicsView(self.tab_2)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(0, 10, 651, 271))
        self.grap.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.graphicsView_3 = QGraphicsView(self.tab_3)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(0, 10, 651, 271))
        self.grap.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.graphicsView_4 = QGraphicsView(self.tab_4)
        self.graphicsView_4.setObjectName(u"graphicsView_4")
        self.graphicsView_4.setGeometry(QRect(0, 10, 651, 271))
        self.grap.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1100, 26))
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuEdit.addAction(self.actionOpen)
        self.menuEdit.addAction(self.actionOpen_2)
        self.menuEdit.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionSave_as)

        self.retranslateUi(MainWindow)

        self.grap.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen_2.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as", None))
        self.GB_caculate.setTitle(QCoreApplication.translate("MainWindow", u"S\u1ed1 li\u1ec7u", None))
        self.label_piston_jour.setText(QCoreApplication.translate("MainWindow", u"H\u00e0nh tr\u00ecnh piston", None))
        self.label_comp_rat.setText(QCoreApplication.translate("MainWindow", u"T\u1ef7 s\u1ed1 n\u00e9n", None))
        self.label_cyl_dm.setText(QCoreApplication.translate("MainWindow", u"\u0110\u01b0\u1eddng k\u00ednh xyalnh", None))
        self.l_extTem.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Vui l\u00f2ng nh\u1eadp nhi\u1ec7t \u0111\u1ed9", None))
        self.label_extTem.setText(QCoreApplication.translate("MainWindow", u"Nhi\u1ec7t \u0111\u1ed9", None))
        self.label_rod_len.setText(QCoreApplication.translate("MainWindow", u"Chi\u1ec1u d\u00e0i thanh truy\u1ec1n", None))
        self.label_air_press.setText(QCoreApplication.translate("MainWindow", u"\u00c1p su\u1ea5t kh\u00ed n\u1ea1p", None))
        self.label_xup_cor.setText(QCoreApplication.translate("MainWindow", u"G\u00f3c \u0111\u00f3ng mu\u1ed9n xuppap", None))
        self.b_clear.setText(QCoreApplication.translate("MainWindow", u"H\u1ee7y b\u1ecf", None))
        self.b_math.setText(QCoreApplication.translate("MainWindow", u"T\u00ednh to\u00e1n", None))
        self.label_Comp_temp_F.setText(QCoreApplication.translate("MainWindow", u"Nhi\u1ec7t \u0111\u1ed9 (\u0111\u1ed9 F)", None))
        self.label_Compression.setText(QCoreApplication.translate("MainWindow", u"\u00c1p su\u1ea5t n\u00e9n", None))
        self.label_Comp_temp_C.setText(QCoreApplication.translate("MainWindow", u"Nhi\u1ec7t \u0111\u1ed9 (\u0111\u1ed9 C)", None))
        self.label_watt.setText(QCoreApplication.translate("MainWindow", u"C\u00f4ng n\u00e9n", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"D\u1eef li\u1ec7u", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Th\u1eddi gian \u0111o", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u0110o xylanh 2", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u0110o xylanh 1", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u0110o xylanh 4", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"(s)", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u0110o xylanh 3", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.GB_Table.setTitle(QCoreApplication.translate("MainWindow", u"B\u1ea3ng s\u1ed1 li\u1ec7u", None))
        self.b_cancel.setText(QCoreApplication.translate("MainWindow", u"Tho\u00e1t", None))
        self.b_confirm.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Ch\u1ea9n \u0111o\u00e1n", None))
        self.grap.setTabText(self.grap.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Xylanh 1", None))
        self.grap.setTabText(self.grap.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Xylanh 2", None))
        self.grap.setTabText(self.grap.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Xylanh 3", None))
        self.grap.setTabText(self.grap.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Xylanh 4", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

