# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'guim.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 798)
        self.QA_actionOpen = QAction(MainWindow)
        self.QA_actionOpen.setObjectName(u"QA_actionOpen")
        self.QA_actionOpen_2 = QAction(MainWindow)
        self.QA_actionOpen_2.setObjectName(u"QA_actionOpen_2")
        self.QA_actionSave = QAction(MainWindow)
        self.QA_actionSave.setObjectName(u"QA_actionSave")
        self.QA_actionSave_as = QAction(MainWindow)
        self.QA_actionSave_as.setObjectName(u"QA_actionSave_as")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget_live_data = QWidget(self.centralwidget)
        self.widget_live_data.setObjectName(u"widget_live_data")
        self.widget_live_data.setGeometry(QRect(10, 430, 381, 231))
        self.PB_pushButton_4 = QPushButton(self.widget_live_data)
        self.PB_pushButton_4.setObjectName(u"PB_pushButton_4")
        self.PB_pushButton_4.setGeometry(QRect(280, 110, 93, 28))
        font = QFont()
        font.setPointSize(8)
        self.PB_pushButton_4.setFont(font)
        self.PB_pushButton_3 = QPushButton(self.widget_live_data)
        self.PB_pushButton_3.setObjectName(u"PB_pushButton_3")
        self.PB_pushButton_3.setGeometry(QRect(280, 70, 93, 28))
        self.PB_pushButton_3.setFont(font)
        self.QL_label_13 = QLabel(self.widget_live_data)
        self.QL_label_13.setObjectName(u"QL_label_13")
        self.QL_label_13.setGeometry(QRect(30, 110, 87, 21))
        font1 = QFont()
        font1.setPointSize(10)
        self.QL_label_13.setFont(font1)
        self.PB_pushButton_5 = QPushButton(self.widget_live_data)
        self.PB_pushButton_5.setObjectName(u"PB_pushButton_5")
        self.PB_pushButton_5.setGeometry(QRect(280, 150, 93, 28))
        self.PB_pushButton_5.setFont(font)
        self.splitter = QSplitter(self.widget_live_data)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(30, 24, 251, 24))
        self.splitter.setFont(font1)
        self.splitter.setOrientation(Qt.Horizontal)
        self.QL_label_16 = QLabel(self.splitter)
        self.QL_label_16.setObjectName(u"QL_label_16")
        self.QL_label_16.setFont(font1)
        self.splitter.addWidget(self.QL_label_16)
        self.doubleSpinBox = QDoubleSpinBox(self.splitter)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setFont(font)
        self.splitter.addWidget(self.doubleSpinBox)
        self.QL_label_17 = QLabel(self.splitter)
        self.QL_label_17.setObjectName(u"QL_label_17")
        self.QL_label_17.setFont(font1)
        self.splitter.addWidget(self.QL_label_17)
        self.QL_label_15 = QLabel(self.widget_live_data)
        self.QL_label_15.setObjectName(u"QL_label_15")
        self.QL_label_15.setGeometry(QRect(30, 184, 87, 21))
        self.QL_label_15.setFont(font1)
        self.PB_pushButton_6 = QPushButton(self.widget_live_data)
        self.PB_pushButton_6.setObjectName(u"PB_pushButton_6")
        self.PB_pushButton_6.setGeometry(QRect(280, 188, 93, 28))
        self.PB_pushButton_6.setFont(font)
        self.QL_label_14 = QLabel(self.widget_live_data)
        self.QL_label_14.setObjectName(u"QL_label_14")
        self.QL_label_14.setGeometry(QRect(30, 147, 87, 21))
        self.QL_label_14.setFont(font1)
        self.QL_label_12 = QLabel(self.widget_live_data)
        self.QL_label_12.setObjectName(u"QL_label_12")
        self.QL_label_12.setGeometry(QRect(30, 73, 87, 21))
        self.QL_label_12.setFont(font1)
        self.PB_progressBar = QProgressBar(self.widget_live_data)
        self.PB_progressBar.setObjectName(u"PB_progressBar")
        self.PB_progressBar.setGeometry(QRect(140, 70, 118, 23))
        self.PB_progressBar.setValue(24)
        self.PB_progressBar_2 = QProgressBar(self.widget_live_data)
        self.PB_progressBar_2.setObjectName(u"PB_progressBar_2")
        self.PB_progressBar_2.setGeometry(QRect(140, 110, 118, 23))
        self.PB_progressBar_2.setValue(24)
        self.PB_progressBar_3 = QProgressBar(self.widget_live_data)
        self.PB_progressBar_3.setObjectName(u"PB_progressBar_3")
        self.PB_progressBar_3.setGeometry(QRect(140, 190, 118, 23))
        self.PB_progressBar_3.setValue(24)
        self.PB_progressBar_4 = QProgressBar(self.widget_live_data)
        self.PB_progressBar_4.setObjectName(u"PB_progressBar_4")
        self.PB_progressBar_4.setGeometry(QRect(140, 150, 118, 23))
        self.PB_progressBar_4.setValue(24)
        self.widget_math = QWidget(self.centralwidget)
        self.widget_math.setObjectName(u"widget_math")
        self.widget_math.setGeometry(QRect(10, 240, 361, 181))
        self.TB_t_Comp_temp_C = QTextBrowser(self.widget_math)
        self.TB_t_Comp_temp_C.setObjectName(u"TB_t_Comp_temp_C")
        self.TB_t_Comp_temp_C.setGeometry(QRect(150, 85, 201, 22))
        self.QL_label_Comp_temp_F = QLabel(self.widget_math)
        self.QL_label_Comp_temp_F.setObjectName(u"QL_label_Comp_temp_F")
        self.QL_label_Comp_temp_F.setGeometry(QRect(20, 111, 115, 21))
        self.QL_label_Comp_temp_F.setFont(font1)
        self.TB_t_Compression = QTextBrowser(self.widget_math)
        self.TB_t_Compression.setObjectName(u"TB_t_Compression")
        self.TB_t_Compression.setGeometry(QRect(150, 56, 201, 22))
        self.TB_t_watt = QTextBrowser(self.widget_math)
        self.TB_t_watt.setObjectName(u"TB_t_watt")
        self.TB_t_watt.setGeometry(QRect(150, 143, 201, 22))
        self.QL_label_Compression = QLabel(self.widget_math)
        self.QL_label_Compression.setObjectName(u"QL_label_Compression")
        self.QL_label_Compression.setGeometry(QRect(20, 53, 89, 21))
        self.QL_label_Compression.setFont(font1)
        self.QL_label_Comp_temp_C = QLabel(self.widget_math)
        self.QL_label_Comp_temp_C.setObjectName(u"QL_label_Comp_temp_C")
        self.QL_label_Comp_temp_C.setGeometry(QRect(20, 82, 116, 21))
        self.QL_label_Comp_temp_C.setFont(font1)
        self.TB_t_Comp_temp_F = QTextBrowser(self.widget_math)
        self.TB_t_Comp_temp_F.setObjectName(u"TB_t_Comp_temp_F")
        self.TB_t_Comp_temp_F.setGeometry(QRect(150, 114, 201, 22))
        self.QL_label_watt = QLabel(self.widget_math)
        self.QL_label_watt.setObjectName(u"QL_label_watt")
        self.QL_label_watt.setGeometry(QRect(20, 140, 69, 21))
        self.QL_label_watt.setFont(font1)
        self.PB_b_clear = QPushButton(self.widget_math)
        self.PB_b_clear.setObjectName(u"PB_b_clear")
        self.PB_b_clear.setGeometry(QRect(180, 10, 93, 28))
        self.PB_b_math = QPushButton(self.widget_math)
        self.PB_b_math.setObjectName(u"PB_b_math")
        self.PB_b_math.setGeometry(QRect(80, 10, 93, 28))
        self.widget_data = QWidget(self.centralwidget)
        self.widget_data.setObjectName(u"widget_data")
        self.widget_data.setGeometry(QRect(10, 10, 371, 221))
        self.QL_label_comp_rat = QLabel(self.widget_data)
        self.QL_label_comp_rat.setObjectName(u"QL_label_comp_rat")
        self.QL_label_comp_rat.setGeometry(QRect(10, 40, 72, 21))
        self.QL_label_comp_rat.setFont(font1)
        self.LE_l_extTem = QLineEdit(self.widget_data)
        self.LE_l_extTem.setObjectName(u"LE_l_extTem")
        self.LE_l_extTem.setGeometry(QRect(191, 9, 178, 24))
        self.LE_l_extTem.setFont(font1)
        self.LE_l_air_press = QLineEdit(self.widget_data)
        self.LE_l_air_press.setObjectName(u"LE_l_air_press")
        self.LE_l_air_press.setGeometry(QRect(191, 195, 178, 23))
        self.LE_l_air_press.setFont(font1)
        self.LE_l_xup_cor = QLineEdit(self.widget_data)
        self.LE_l_xup_cor.setObjectName(u"LE_l_xup_cor")
        self.LE_l_xup_cor.setGeometry(QRect(191, 164, 178, 24))
        self.LE_l_xup_cor.setFont(font1)
        self.QL_label_extTem = QLabel(self.widget_data)
        self.QL_label_extTem.setObjectName(u"QL_label_extTem")
        self.QL_label_extTem.setGeometry(QRect(10, 9, 63, 21))
        self.QL_label_extTem.setFont(font1)
        self.LE_l_cyl_dm = QLineEdit(self.widget_data)
        self.LE_l_cyl_dm.setObjectName(u"LE_l_cyl_dm")
        self.LE_l_cyl_dm.setGeometry(QRect(191, 102, 178, 24))
        self.LE_l_cyl_dm.setFont(font1)
        self.LE_l_comp_rat = QLineEdit(self.widget_data)
        self.LE_l_comp_rat.setObjectName(u"LE_l_comp_rat")
        self.LE_l_comp_rat.setGeometry(QRect(191, 40, 178, 24))
        self.LE_l_comp_rat.setFont(font1)
        self.LE_l_rod_len = QLineEdit(self.widget_data)
        self.LE_l_rod_len.setObjectName(u"LE_l_rod_len")
        self.LE_l_rod_len.setGeometry(QRect(191, 133, 178, 24))
        self.LE_l_rod_len.setFont(font1)
        self.QL_label_xup_cor = QLabel(self.widget_data)
        self.QL_label_xup_cor.setObjectName(u"QL_label_xup_cor")
        self.QL_label_xup_cor.setGeometry(QRect(10, 164, 174, 21))
        self.QL_label_xup_cor.setFont(font1)
        self.QL_label_piston_jour = QLabel(self.widget_data)
        self.QL_label_piston_jour.setObjectName(u"QL_label_piston_jour")
        self.QL_label_piston_jour.setGeometry(QRect(10, 71, 141, 21))
        self.QL_label_piston_jour.setFont(font1)
        self.QL_label_rod_len = QLabel(self.widget_data)
        self.QL_label_rod_len.setObjectName(u"QL_label_rod_len")
        self.QL_label_rod_len.setGeometry(QRect(10, 133, 167, 21))
        self.QL_label_rod_len.setFont(font1)
        self.LE_l_piston_jour = QLineEdit(self.widget_data)
        self.LE_l_piston_jour.setObjectName(u"LE_l_piston_jour")
        self.LE_l_piston_jour.setGeometry(QRect(191, 71, 178, 24))
        self.LE_l_piston_jour.setFont(font1)
        self.QL_label_air_press = QLabel(self.widget_data)
        self.QL_label_air_press.setObjectName(u"QL_label_air_press")
        self.QL_label_air_press.setGeometry(QRect(10, 195, 115, 21))
        self.QL_label_air_press.setFont(font1)
        self.QL_label_cyl_dm = QLabel(self.widget_data)
        self.QL_label_cyl_dm.setObjectName(u"QL_label_cyl_dm")
        self.QL_label_cyl_dm.setGeometry(QRect(10, 102, 136, 21))
        self.QL_label_cyl_dm.setFont(font1)
        self.w_comment = QWidget(self.centralwidget)
        self.w_comment.setObjectName(u"w_comment")
        self.w_comment.setGeometry(QRect(390, 10, 681, 381))
        self.TW_tableWidget = QTableWidget(self.w_comment)
        if (self.TW_tableWidget.columnCount() < 5):
            self.TW_tableWidget.setColumnCount(5)
        if (self.TW_tableWidget.rowCount() < 5):
            self.TW_tableWidget.setRowCount(5)
        self.TW_tableWidget.setObjectName(u"TW_tableWidget")
        self.TW_tableWidget.setGeometry(QRect(10, 10, 661, 361))
        self.TW_tableWidget.setRowCount(5)
        self.TW_tableWidget.setColumnCount(5)
        self.widget_grap = QWidget(self.centralwidget)
        self.widget_grap.setObjectName(u"widget_grap")
        self.widget_grap.setGeometry(QRect(400, 400, 671, 301))
        self.splitter_2 = QSplitter(self.widget_grap)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(30, 10, 181, 22))
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.splitter_3 = QSplitter(self.splitter_2)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.QL_label_19 = QLabel(self.splitter_3)
        self.QL_label_19.setObjectName(u"QL_label_19")
        self.QL_label_19.setFont(font1)
        self.splitter_3.addWidget(self.QL_label_19)
        self.CB_comboBox_2 = QComboBox(self.splitter_3)
        self.CB_comboBox_2.addItem("")
        self.CB_comboBox_2.addItem("")
        self.CB_comboBox_2.addItem("")
        self.CB_comboBox_2.addItem("")
        self.CB_comboBox_2.setObjectName(u"CB_comboBox_2")
        self.CB_comboBox_2.setFont(font)
        self.splitter_3.addWidget(self.CB_comboBox_2)
        self.splitter_2.addWidget(self.splitter_3)
        self.TB_t_comment = QTextBrowser(self.widget_grap)
        self.TB_t_comment.setObjectName(u"TB_t_comment")
        self.TB_t_comment.setGeometry(QRect(10, 40, 641, 251))
        self.widget_5 = QWidget(self.centralwidget)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(770, 700, 271, 41))
        self.PB_b_cancel = QPushButton(self.widget_5)
        self.PB_b_cancel.setObjectName(u"PB_b_cancel")
        self.PB_b_cancel.setGeometry(QRect(140, 10, 93, 28))
        font2 = QFont()
        font2.setBold(True)
        font2.setWeight(75)
        self.PB_b_cancel.setFont(font2)
        self.PB_b_confirm = QPushButton(self.widget_5)
        self.PB_b_confirm.setObjectName(u"PB_b_confirm")
        self.PB_b_confirm.setGeometry(QRect(40, 10, 93, 28))
        self.PB_b_confirm.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1100, 26))
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuEdit.addAction(self.QA_actionOpen)
        self.menuEdit.addAction(self.QA_actionOpen_2)
        self.menuEdit.addAction(self.QA_actionSave)
        self.menuEdit.addAction(self.QA_actionSave_as)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.QA_actionOpen.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.QA_actionOpen_2.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.QA_actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.QA_actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as", None))
        self.PB_pushButton_4.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.PB_pushButton_3.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.QL_label_13.setText(QCoreApplication.translate("MainWindow", u"\u0110o xylanh 2", None))
        self.PB_pushButton_5.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.QL_label_16.setText(QCoreApplication.translate("MainWindow", u"Th\u1eddi gian \u0111o", None))
        self.QL_label_17.setText(QCoreApplication.translate("MainWindow", u"(s)", None))
        self.QL_label_15.setText(QCoreApplication.translate("MainWindow", u"\u0110o xylanh 4", None))
        self.PB_pushButton_6.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.QL_label_14.setText(QCoreApplication.translate("MainWindow", u"\u0110o xylanh 3", None))
        self.QL_label_12.setText(QCoreApplication.translate("MainWindow", u"\u0110o xylanh 1", None))
        self.QL_label_Comp_temp_F.setText(QCoreApplication.translate("MainWindow", u"Nhi\u1ec7t \u0111\u1ed9 (\u0111\u1ed9 F)", None))
        self.QL_label_Compression.setText(QCoreApplication.translate("MainWindow", u"\u00c1p su\u1ea5t n\u00e9n", None))
        self.QL_label_Comp_temp_C.setText(QCoreApplication.translate("MainWindow", u"Nhi\u1ec7t \u0111\u1ed9 (\u0111\u1ed9 C)", None))
        self.QL_label_watt.setText(QCoreApplication.translate("MainWindow", u"C\u00f4ng n\u00e9n", None))
        self.PB_b_clear.setText(QCoreApplication.translate("MainWindow", u"H\u1ee7y b\u1ecf", None))
        self.PB_b_math.setText(QCoreApplication.translate("MainWindow", u"T\u00ednh to\u00e1n", None))
        self.QL_label_comp_rat.setText(QCoreApplication.translate("MainWindow", u"T\u1ef7 s\u1ed1 n\u00e9n", None))
        self.QL_label_extTem.setText(QCoreApplication.translate("MainWindow", u"Nhi\u1ec7t \u0111\u1ed9", None))
        self.QL_label_xup_cor.setText(QCoreApplication.translate("MainWindow", u"G\u00f3c \u0111\u00f3ng mu\u1ed9n xuppap", None))
        self.QL_label_piston_jour.setText(QCoreApplication.translate("MainWindow", u"H\u00e0nh tr\u00ecnh piston", None))
        self.QL_label_rod_len.setText(QCoreApplication.translate("MainWindow", u"Chi\u1ec1u d\u00e0i thanh truy\u1ec1n", None))
        self.QL_label_air_press.setText(QCoreApplication.translate("MainWindow", u"\u00c1p su\u1ea5t kh\u00ed n\u1ea1p", None))
        self.QL_label_cyl_dm.setText(QCoreApplication.translate("MainWindow", u"\u0110\u01b0\u1eddng k\u00ednh xyalnh", None))
        self.QL_label_19.setText(QCoreApplication.translate("MainWindow", u"Ch\u1ea9n \u0111o\u00e1n", None))
        self.CB_comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"Xylanh 1", None))
        self.CB_comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Xylanh 2", None))
        self.CB_comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"Xylanh 3", None))
        self.CB_comboBox_2.setItemText(3, QCoreApplication.translate("MainWindow", u"Xylanh 4", None))

        self.PB_b_cancel.setText(QCoreApplication.translate("MainWindow", u"Tho\u00e1t", None))
        self.PB_b_confirm.setText(QCoreApplication.translate("MainWindow", u"X\u00e1c nh\u1eadn", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

